type: pipeline
experiment_name: tfch8
jobs:

  get_data:
    type: component
    component: azureml:download-url:10
    compute: azureml:cpu-cluster
    inputs:
      url: "https://storage.googleapis.com/laurencemoroney-blog.appspot.com/irish-lyrics-eof.txt"
    outputs:
      raw_data:
        mode: mount
  
  train:
    type: component
    component: azureml:train-text-prediction:10
    compute: azureml:gpu-cluster
    inputs:
      training_data: ${{jobs.get_data.outputs.raw_data}}
      epochs: 10
    outputs:
      trained_model:
        mode: mount

  score:
    type: command
    compute: azureml:gpu-cluster
    inputs:
      token_data: ${{jobs.get_data.outputs.raw_data}}
      model: ${{jobs.train.outputs.trained_model}}
      score: 
        dataset:
          local_path: ./score-data
      predict_count: 1
    outputs:
      scored_data:
        mode: mount
    environment: azureml:AzureML-tensorflow-2.4-ubuntu18.04-py37-cuda11-gpu:18
    code: 
      local_path: ./
    command: >-
      python ./irishsongs-score.py 
      --data ${{inputs.token_data}} 
      --predict_count ${{inputs.predict_count}} 
      --model ${{inputs.model}}
      --score ${{inputs.score}}
      --output ${{outputs.scored_data}}
