type: pipeline

experiment_name: tfbook-chapter8

settings:
  default_compute: azureml:amlarc-cluster

jobs:
  get_data:
    type: command
    #compute: azureml:cpu-cluster
    inputs:
      url: "https://storage.googleapis.com/laurencemoroney-blog.appspot.com/irish-lyrics-eof.txt"
      #url: "https://www.gutenberg.org/cache/epub/5200/pg5200.txt"
    outputs:
      raw_data:
        type: uri_folder
        mode: mount
    environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu:3
    command: wget ${{inputs.url}} -P ${{outputs.raw_data}}
  train:
    type: command
    #compute: azureml:gpu-cluster
    inputs:
      training_data: ${{parent.jobs.get_data.outputs.raw_data}}
      epochs: 10
    outputs:
      trained_model:
        type: uri_folder
        mode: mount
    environment: azureml:AzureML-tensorflow-2.4-ubuntu18.04-py37-cuda11-gpu:18
    code: ./
    command: >-
      python ./irishsongs-mlflow.py --data ${{inputs.training_data}} 
      --epochs ${{inputs.epochs}} --model ${{outputs.trained_model}}
  score:
    type: command
    #compute: azureml:gpu-cluster
    inputs:
      token_data: ${{parent.jobs.get_data.outputs.raw_data}}
      model: ${{parent.jobs.train.outputs.trained_model}}
      score: 
        type: uri_folder
        path: ./score-data
      predict_count: 1
    outputs:
      scored_data:
        type: uri_folder
        mode: mount
    environment: azureml:AzureML-tensorflow-2.4-ubuntu18.04-py37-cuda11-gpu:18
    code: ./
    command: >-
      python ./irishsongs-score.py --data ${{inputs.token_data}} 
      --predict_count ${{inputs.predict_count}} --model ${{inputs.model}}
      --score ${{inputs.score}} --output ${{outputs.scored_data}}
